_options:
  content:
    styles: /editor.css
    blockquote: true
    horizontalrule: true
    format: p h1 h2 h3 h4 h5 h6 img
    bold: true
    italic: true
    numberedlist: true
    bulletedlist: true
    code: true
    table: true
    right: right
    center: center
    left: left
    embed: true
    link: true
    undo: true
    redo: true
    underline: true
    strike: true
    image: true

  content_html:
    styles: /editor.css
    blockquote: true
    horizontalrule: true
    format: p h1 h2 h3 h4 h5 h6 img
    bold: true
    italic: true
    numberedlist: true
    bulletedlist: true
    code: true
    table: true
    right: right
    center: center
    left: left
    embed: true
    link: true
    undo: true
    redo: true
    underline: true
    strike: true
    image: true

# development
url: "" # Your main domain
baseurl: ""  # Optional, add this if you use a subpath on your main domain

title: "Casa Seda"
description: "Discover Casa Seda in Bali, a refined dining retreat blending Spanish warmth with Asian calm. Enjoy exquisite fusion dishes in an ambiance that feels both luxurious and welcoming."
email: "hello@casa-seda.refinedislandcreations.com"
twitter: "casasedabali"
instagram: "casasedabali"
logo: "/icons/apple-touch-icon.png"

# production
url: "https://casa-seda.refinedislandcreations.com" # Your main domain
baseurl: ""  # Optional, add this if you use a subpath on your main domain
plugins:
  - jekyll-sitemap
  